### ISSUE TITLE
Increasing RTO for syncLeads

### ISSUE THREAD

**Issue by vivek907** [jepcastelein/marketo-rest-python#70]
Can we programmatically set the request time out value for the requests library within the syncLead API call to allow for longer processing of large syncLead requests? As per the specifications of the syncLead API call, it can take up to 90 seconds for a call to process. The current default time out value is set to 30seconds in the requests library. Hence, being able to programmatically set the value will allow us to set this value for large API requests (upwards of 200+ fields in a single syncLead for a single record).

**Comment by jepcastelein** [comment]
Hey Vivek! I don't think there is an explicit timeout configured. If you look at https://github.com/jepcastelein/marketo-rest-python/blob/master/marketorestpython/helper/http_lib.py, it is pretty vanilla usage of requests. It is my understanding that there is no default timeout in requests: 
https://docs.python-requests.org/en/master/user/advanced/#timeouts
`By default, requests do not time out unless a timeout value is set explicitly. `
Could your issue be caused by something else?

**Comment by vivek907** [comment]
Hello Jep! interesting - I will look a bit deeper to see what else can be done on the code end. The basic crux of the issue is that the API returns null response for a very large request (even if the request itself is less than 1MB). Hence, I was thinking whether the requests timeout has anything to do with this.

**Comment by jepcastelein** [comment]
timeout is now configurable thanks to a code contribution
